name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.12, 1.13, 1.14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-contrib/golangci-lint@v1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.version }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}

      - run: go get -v -d ./...
      - run: go build -v ./...

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/publish-docker-github-action@2.13
        with:
          name: kevinpollet/serge
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
