name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.12, 1.13, 1.14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-contrib/golangci-lint@v1
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.version }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}

      - run: go get -v -d ./...
      - run: go build -v ./...
